### ISSUE TITLE
Callback error OAuthAccountNotLinked

### ISSUE THREAD

**Issue by tomn-git** [mattsince87/nextauth-prisma#11]
Hi Matt... thanks for the template. New to React and still figuring things out.

Deployed the template correctly to Vercel at https://mystoryheroapp.vercel.app/. 

First time i signin (on a fresh install, 0 users in the db), i get a "Callback" error on the callback URL. 
But, I now have 1 record in users table.

When I refresh and try again, I'm getting an OAuthAccountNotLinked when calling back from GitHub OAuth.

0 records in accounts and subscriptions tables.

Many thanks.

**Comment by jcopperman** [comment]
Hey @tomn-git 

I think your GitHub OAuth is not configured correctly. The following works for me:
`GitHubProvider({
      clientId: process.env.GITHUB_ID ?? '',
      clientSecret: process.env.GITHUB_SECRET ?? '',
      httpOptions: {
        timeout: 40000,
      },
      authorization: {
        params: {
          url: 'https://github.com/login/oauth/authorize',
          prompt: 'consent',
          response_type: 'code',
        },
      },
    }),`

**Comment by uixmat** [comment]
Hey @tomn-git, as @jcopperman mentioned it sounds like you might not have updated your callback url in your GitHub application which is why you're experiencing callback errors despite a user being created

**Comment by tomn-git** [comment]
Yes, sorry... I was trying to integrate into an existing Supabase database and perhaps the camelCase to snake_case mappings were causing issues.

Now I just cloned your repo with a new Supabase database and same GitHub app and worked. Thanks.
