### ISSUE TITLE
Add Clerk as auth provider

### ISSUE THREAD

**Issue by jcopperman** [mattsince87/nextauth-prisma#13]
Would it be possible to retro fit Clerk's user management (signup/signin/profile) with the existing auth code? 

I ran into some trouble (more skill limitations) trying to add auth providers to the existing Github provider but am running in to so many errors that I wondered if it would not be easier to integrate Clerk into your implementation which is fully managed auth?

I would do this myself and create a PR but I am not confident enough to do this without undoing your good work with Lemon Squeezy, which is why I came to fork :) .

Have you got something like Clerk on your roadmap or any advice on how to integrate Clerk with this?

Thanks for the awesome work and killer template!

**Comment by uixmat** [comment]
@jcopperman I don't have anything roadmapped for Clerk but that said I may look back into it and potentially add it in
